[package]
name = "pixel-wars"
version = "0.1.0"
edition = "2021"

[dependencies]
turbo = { version = "1.6.0-alpha.4", package = "turbo-genesis-sdk", path = "/Users/alexanderfeigenbaum/Documents/GitHub/turbo-genesis-sdk" }
csv = "1.1"

[lib]
crate-type = ["cdylib"]
