[package]
name = "card-search"
version = "1.0.0"
edition = "2021"

[dependencies]
borsh = "1.5.7"
turbo = { version = "^3.1.0", package = "turbo-genesis-sdk" }
turbo-genesis-sdk = "3.1.1"

[lib]
crate-type = ["cdylib"]

[lints.rust]
unexpected_cfgs = { level = "allow" }
