[package]
name = "card-search"
version = "1.0.0"
edition = "2021"

[dependencies]
turbo = { version = "5.1.0", package = "turbo-genesis-sdk" }

[lib]
crate-type = ["cdylib"]

[lints.rust]
unexpected_cfgs = { level = "allow" }
