[package]
name = "sausagers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
turbo = { version = ">=1.5.2", package = "turbo-genesis-sdk" }

[lib]
crate-type = ["cdylib"]
